meta_product_name: "Coding Buddies"
meta_title: "FindACodingBuddy - improve your coding skills and expand your network"
meta_description: "Improve your coding skills and expand your network building amazing projects"
meta_image: "home_page_banner_pic.jpg" # should exist in `app/assets/images/`